### PR TITLE
Updated property / Class specifiics in the DocumentSymbolProvider & Snippets

### PR DESCRIPTION
**Pull request by jaunito76**
Recommend accepting the changes in the DocumentSymbolProvider, the snippets are a bit more for use in my coding projects, but I think that they would be useful to many users so I included them in the pull request. I am happy to discuss, I have been searching for a way to make this better with a language provider, but I think that might be a bit beyond my time and capability at this point. Let me know what you think

CJ

### CODE REVIEW

**Comment by spences10** [comment]
Hi, thanks for your PR

> bit more for use in my coding projects, but I think that they would be useful to many users 

If this is for your coding projects then it may be of benefit to you to fork the repo and make your own extension.

If you can give an explanation as to why this would be useful to many users that would be great.

Currently I don't see what this is adding for other users.

And yeah, we all want that language provider magic too

**Comment by jaunito76** [comment]
What I added is support for classes within vba, in the current version you do not have property included in the syntax highlighting.

**Comment by spences10** [comment]
Sorry, had to close this as I haven't time to go through the changes and don't feel that you gave a good enough explanation as to why you've added several new files what they're there for etc.

Thanks

**Comment by jaunito76** [comment]
Sounds good, just a reminder that you don’t have the ‘Property (Get|Set|Let)’ as a keyword in the main branch version. My pull request had that fix in it, I did add to the vba.json in the snippets, but that is not that important, but the rest would make it easier to use.

 

-CJ

**Comment by spences10** [comment]
I'll happily accept a PR with that on it 🙏 

Also, @jaunito76 have you seen [Excel Live Server]? 

[Excel Live Server]:https://marketplace.visualstudio.com/items?itemName=local-smart.excel-live-server

**Pull request closed without merging**
