### PR TITLE
Support for 'Const' and 'Static' variables

### PR DESCRIPTION
**Pull request by scottmwyant**
Add formatting support for constants and static variables.  Make these other types of "variables" get the same formatting as the 'Dim' keyword.  Note that I did not update any version numbers.  Also, the diff on GitHub is showing a little funny. Line 102 is moved down to line 132 (added 'Static' keyword).

### CODE REVIEW

**Comment by spences10** [comment]
Thanks for this @scottmwyant I'll take a look when I'm next push a version :ok_hand:

**Comment by spences10** [comment]
@scottmwyant have you tested this?

**Comment by scottmwyant** [comment]
@spences10 Yes, I have this edit in my local version of the file.  Also, you might want to add a `Option Compare Text|` after `|Option Explicit|` on line 132.  I'm in the habit of setting those two options as the first two lines of a module.  Best, - SW

**Comment by spences10** [comment]
Great, can I pull the changes from your branch?

**Comment by scottmwyant** [comment]
Yes. I committed the bit about option compare text after last night. You should be able to merge.

**Comment by spences10** [comment]
Ok, great, much appreciated @scottmwyant 

I'm going to have to take a look at getting the extension onto the marketplace again, I have no recollection of how to do it 🙃 

Apologies I'm going to have to keep it open until I move it to the marketplace, if I merge it now I'll forget and it'll never be done - hope you understand 🙏

**Comment by spences10** [comment]
Hey @scottmwyant could you pull the latest changes and add your to this PR please?

Apologies I should have merged your changes first 🙃

**Pull request closed without merging**
